language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - if [[ $DISABLE_ADD_TRAVIS_PHP_INI != 'true' ]]; then phpenv config-add .travis/php.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

before_script:
  - mysql -e 'create database test_database_name;'

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --configuration $TRAVIS_BUILD_DIR/phpunit.xml.travis --coverage-php $TRAVIS_BUILD_DIR/build/logs/coverage/coverage-phpunit.cov; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit --configuration $TRAVIS_BUILD_DIR/phpunit.xml.travis ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then  ./vendor/bin/php-cs-fixer fix -v --diff --dry-run --config-file ./.php_cs ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpcov merge --clover $TRAVIS_BUILD_DIR/build/logs/clover.xml $TRAVIS_BUILD_DIR/build/logs/coverage ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls -v --config .coveralls.yml --coverage_clover=$TRAVIS_BUILD_DIR/build/logs/clover.xml; fi

notifications:
  email:
  - and-rey2@yandex.ru

services:
  - mysql
